# This file was generated by GoReleaser. DO NOT EDIT.
cask "vpscriber" do
  name "vpscriber"
  desc "VPS version - Audio transcription service using WhisperX with speaker diarization"
  homepage "https://github.com/szern/vpscriber"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vpscriber"
  depends_on formula: [
      "uv",
    ]

  on_linux do
    on_intel do
      url "https://github.com/Szern/VPScriber/releases/download/#{version}/VPScriber_Linux_x86_64.tar.gz"
      sha256 "a35430e740af5aff3025771781236e5dc80fdc8418e8d417fa5456ed95d34f43"
    end
    on_arm do
      url "https://github.com/Szern/VPScriber/releases/download/#{version}/VPScriber_Linux_arm64.tar.gz"
      sha256 "a4a9725b246cf24c56fc8f0e1f8f478fa42946e45dbdbc9a85ede1e1d2aa7ff6"
    end
  end

  caveats do
    "Scriberr requires Python 3.11+ for transcription features."
    "Install with: brew install python@3.11"
    ""
    "To get started:"
    "1. Run: scriberr"
    "2. Open: http://localhost:8080"
    ""
    "The app will auto-configure itself on first run."
  end

  # No zap stanza required
end
